version: appvayor.{build}

os:
    - Visual Studio 2015
    - Visual Studio 2017

configuration:
    - Release
    - Debug

clone_folder: c:\dev\bayes-filters-lib

shallow_clone: true

clone_depth: 5

cache:
    - 'C:\Tools\vcpkg\installed'
    - 'C:\Tools\vcpkg\packages'

init:
    - ps: git config --global core.autocrlf input
    - ps: if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2015") {$env:CMAKE_GENERATOR="Visual Studio 14 2015 Win64"}
    - ps: if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2017") {$env:CMAKE_GENERATOR="Visual Studio 15 2017 Win64"}
    - ps: echo CMAKE_GENERATOR=$env:CMAKE_GENERATOR
    - ps: $env:VCPKG_DEFAULT_TRIPLET="x64-windows"
    - ps: echo VCPKG_DEFAULT_TRIPLET=$env:VCPKG_DEFAULT_TRIPLET
    - ps: echo CONFIGURATION=$env:CONFIGURATION

install:
    - ps: vcpkg update
    - ps: vcpkg install eigen3
    - ps: vcpkg install opencv

build:

build_script:
    - ps: cd c:\dev\bayes-filters-lib
    - ps: mkdir build
    - ps: cd build
    - ps: cmake -G "$env:CMAKE_GENERATOR" -DCMAKE_TOOLCHAIN_FILE=c:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_TESTING:BOOL=ON ..
    - ps: cmake --build . --config $env:CONFIGURATION --target ALL_BUILD

after_build:
    - ps: cmake --build . --config $env:CONFIGURATION --target INSTALL

test_script:
    - ps: ctest -C $env:CONFIGURATION -VV
